[package]
name = "full_moon"
version = "0.3.1"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
description = "A lossless Lua 5.1 parser"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/Kampfkarren/full-moon"
categories = ["parsing"]
keywords = ["lua", "parser", "lua51"]
edition = "2018"

[features]
default = ["serde"]
no-source-tests = []
only-source-tests = []

[dependencies]
full_moon_derive = { path = "./full-moon-derive", version = "0.1.1" }
generational-arena = "0.2"
itertools = "0.8"
lazy_static = "1.3"
regex = "1.1"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_json = "1.0"