[package]
name = "full_moon"
version = "0.1.0"
authors = ["Kampfkarren"]
description = "A lossless Lua 5.1 parser"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/Kampfkarren/full-moon"
edition = "2018"

[features]
default = ["serde", "visitors"]
no-source-tests = []
only-source-tests = []
visitors = []

[dependencies]
lazy_static = "1.3"
regex = "1.1"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_json = "1.0"